---
title: Project Name
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
- scope:
    path: ''
  values:
    layout: default
    show-avatar: true
gems:
- jekyll-paginate
- jekyll-feed
url: ''
enforce_ssl: ''
baseurl: "/jekyllBasic"
keywords: test1, test2, etc
desc: Sample Description
avatar: "/img/avatar.jpg"
nav-links:
  Home: ''
  About Me: aboutme
  Contact: contact
profile:
  name: Babji Chetty
  email: Your-Email
  facebook: your-fb-id
  github: your-github-id
  twitter: your-twitter-id
  linkedin: your-linkedin-id
  stackoverflow: your-stackoverflow-id
pretty-url: bchetty.com
disqus: Your-Disqus-Id
google_analytics: Your-GA-Id
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/blog/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
created-by: Babji, Chetty
creator-url: https://bchetty.com
